# OpenMP projects should set the environment variable OMP_NUM_THREADS to a reasonably small value (say, 4). 
dist: trusty
sudo : false

notifications:
    slack: veg-igem:rqQd95zjTuZoRNElekQx2CLf
    email:
        recipients:
            - spond@temple.edu
            - steven@stevenweaver.org
        on_success: change
        on_failure: always

branches:
  only:
    - master
    - beta
    - develop

env:
  - envSpecificTest="bash ./test_kwargs.sh"
  - envSpecificTest="bash ./run_unit_tests.sh"
  - envSpecificTest="export PATH=$PATH:$(pwd); cd; git clone https://gitlab.com/rdvelazquez/testiphy.git; cd testiphy; ./testiphy HYPHYMP"
  - envSpecificTest="./HYPHYMP LIBPATH=`pwd`/res/ tests/hbltests/libv3/SLAC.wbf"
  - envSpecificTest="./HYPHYMP LIBPATH=`pwd`/res/ tests/hbltests/libv3/SLAC-partitioned.wbf"
  - envSpecificTest="./HYPHYMP LIBPATH=`pwd`/res/ tests/hbltests/libv3/FEL.wbf"
  - envSpecificTest="./HYPHYMP MEME --alignment ./tests/hbltests/data/CD2.nex"
  #- envSpecificTest=./HYPHYMP LIBPATH=`pwd`/res/ tests/hbltests/libv3/MEME-partitioned.wbf
  - envSpecificTest="./HYPHYMP LIBPATH=`pwd`/res/ tests/hbltests/libv3/FUBAR.wbf"
  - envSpecificTest="./HYPHYMP LIBPATH=`pwd`/res/ tests/hbltests/libv3/RELAX.wbf"
  - envSpecificTest="./HYPHYMP LIBPATH=`pwd`/res/ tests/hbltests/libv3/aBSREL.wbf"
  - envSpecificTest="./HYPHYMP BUSTED --alignment ./tests/hbltests/data/CD2.nex --srv No --branches Internal"

language: c++
compiler: 
  - gcc

addons:
  apt:
    sources:
        - llvm-toolchain-precise
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
    packages:
        - g++-6
        - gcc-6

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
  - cmake . 
  - make HYPHYMP

script: 
  - export OMP_NUM_THREADS=4
  - eval $envSpecificTest
