# This is a basic workflow to help you get started with Actions

name: Benchmark

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ klevitz-dev ]
  pull_request:
    branches: [ klevitz-dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build_Make_run_Benchmarks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
            
    - name: Compile Make
      run: |
        ls
        pwd
        cmake .
        make -j all
        
    - name: Install and run Hyperfine
      run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.9.0/hyperfine_1.9.0_amd64.deb
          sudo dpkg -i hyperfine_1.9.0_amd64.deb
          # hyperfine --min-runs 5 'sleep 0.2' 'sleep 3.2'
          # hyperfine -i --show-output 'make test'
          hyperfine "./HYPHYMP 'tests/hbltests/SimpleOptimizations/SmallCodon.bf'"
          hyperfine "./HYPHYMP 'tests/hbltests/SimpleOptimizations/IntermediateProtein.bf'"
          hyperfine "./HYPHYMP 'tests/hbltests/libv3/SLAC.wbf'"
          hyperfine "./HYPHYMP 'tests/hbltests/libv3/SLAC-partitioned.wbf'"
          hyperfine "./HYPHYMP 'tests/hbltests/libv3/FEL.wbf'"
          hyperfine "./HYPHYMP 'tests/hbltests/libv3/MEME.wbf'"
          hyperfine "./HYPHYMP 'tests/hbltests/libv3/BUSTED.wbf'"
          hyperfine "./HYPHYMP 'tests/hbltests/libv3/BUSTED-SRV.wbf'"
          hyperfine "./HYPHYMP 'tests/hbltests/libv3/RELAX.wbf'"
          hyperfine "./HYPHYMP 'tests/hbltests/libv3/FUBAR.wbf'"
          hyperfine "./HYPHYMP 'tests/hbltests/libv3/BGM.wbf'"
          hyperfine "./HYPHYMP 'tests/hbltests/libv3/CFEL.wbf'"
          hyperfine "./HYPHYMP 'tests/hbltests/libv3/GARD.wbf'"
          hyperfine "./HYPHYMP 'tests/hbltests/libv3/FADE.wbf'"
