name: WebAssembly Build
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-wasm:
    name: Build WebAssembly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 'latest'
          
      - name: Verify Emscripten installation
        run: |
          emcc --version
          
      - name: Configure and build with Emscripten
        run: |
          # Build with Emscripten
          mkdir -p build
          cd build
          emcmake cmake .. -DCMAKE_EXE_LINKER_FLAGS="-sTOTAL_STACK=2097152 -O2 -sASSERTIONS=1 -sMODULARIZE=1 -sALLOW_MEMORY_GROWTH -sFORCE_FILESYSTEM=1 -sEXIT_RUNTIME=0 -s EXPORTED_RUNTIME_METHODS=[\"callMain\",\"FS\",\"PROXYFS\",\"WORKERFS\",\"UTF8ToString\",\"getValue\",\"AsciiToString\"] -lworkerfs.js -lproxyfs.js -s INVOKE_RUN=0 -s ENVIRONMENT=\"web,worker\" -fwasm-exceptions --preload-file ../res@/hyphy --preload-file ../tests/hbltests@/tests"
          emmake make -j hyphy
          
      - name: Display build artifacts
        run: |
          cd build
          ls -la
          
      - name: Upload WASM artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hyphy-wasm
          path: |
            build/hyphy.js
            build/hyphy.wasm
            build/hyphy.data
          retention-days: 14